stages:
  - test
  - pre-build
  - build
  - deploy

unit-test:
  stage: test
  image: registry.bukalapak.io/sre/gudang/pre-build/golang:0.0.3
  before_script:
    - mkdir -p /go/src/github.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR /go/src/github.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - cd /go/src/github.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - make dep
  artifacts:
    untracked: false
    paths:
      - deploy/_output
  script:
    - make test

build-image:
  stage: pre-build
  image: registry.bukalapak.io/sre/gudang/pre-build/golang:0.0.3
  dependencies:
    - unit-test
  before_script:
    - mkdir -p /go/src/github.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR /go/src/github.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - cd /go/src/github.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
    - make dep
  artifacts:
    untracked: false
    paths:
      - deploy/_output
  script:
    - make compile
    - make consul

push-image:
  stage: build
  image: registry.bukalapak.io/sre/gudang/build/docker:0.0.1
  dependencies:
    - build-image
  variables:
    DOCKER_HOST: 172.16.8.88:2375
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  artifacts:
    untracked: false
    paths:
      - deploy/_output
  script:
    - make build
    - make push

generate-deployment:
  stage: build
  image: registry.bukalapak.io/sre/gudang/build/kubelize:0.0.1
  dependencies:
    - build-image
  artifacts:
    untracked: false
    paths:
      - deploy/_output
  script:
    - make deployment

deploy-sandbox:
  stage: deploy
  image: registry.bukalapak.io/sre/gudang/deployment:0.0.1
  dependencies:
    - push-image
  when: manual
  script:
    - kubectl config use-context staging-cluster
    - ENV=sandbox make sandbox

deploy-canary:
  stage: deploy
  image: registry.bukalapak.io/sre/gudang/deployment:0.0.1
  dependencies:
    - push-image
  when: manual
  script:
    - ENV=canary make canary

deploy-production:
  stage: deploy
  image: registry.bukalapak.io/sre/gudang/deployment:0.0.1
  dependencies:
    - push-image
  when: manual
  script:
    - ENV=production make production
