stages:
- test
- pre-build
- build
- deployment

variables:
  VAR_KUBE_CONTEXT: $ENV  
  MODCACHEDIR: $CI_PROJECT_DIR/.gomod


.prep-go-dir: &prep-go-dir
- mkdir -p $MODCACHEDIR $GOPATH/pkg
- ln -s $MODCACHEDIR $GOPATH/pkg/mod
- export GO111MODULE=on
- mkdir -p $GOPATH/src/github.com/bukalapak
- ln -s $CI_PROJECT_DIR $GOPATH/src/github.com/bukalapak
- cd $GOPATH/src/github.com/bukalapak/$CI_PROJECT_NAME

test:
  stage: test
  image: registry.bukalapak.io/sre/gudang/golang:2.0.0
  before_script: *prep-go-dir
  script:
  - make test
  cache:
    key: gomod
    paths:
    - $MODCACHEDIR

compile:
  stage: pre-build
  image: registry.bukalapak.io/sre/gudang/golang:2.0.0
  only:
  - triggers
  before_script: *prep-go-dir
  script:
  - make compile
  artifacts:
    expire_in: 1 day
    paths:
    - deploy/_output
  cache:
    key: gomod
    paths:
    - $MODCACHEDIR
    policy: pull

build-image:
  stage: build
  image: registry.bukalapak.io/sre/gudang/docker:1.0.0
  tags:
  - build-image
  only:
  - triggers
  script:
  - export VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - make build push

.deploy-template: &deploy-template
  stage: deployment
  image: registry.bukalapak.io/sre/gudang/deployment:2.2.0
  tags:
  - bare-metal
  only:
  - triggers
  script:
  - export VERSION=${CI_COMMIT_TAG:-$CI_COMMIT_SHA}
  - kubectl config use-context $VAR_KUBE_CONTEXT
  - make deploy

deploy:
  <<: *deploy-template

deploy-service:
  <<: *deploy-template
  allow_failure: true
  when: manual
  variables:
    FILE: service
