apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-xample-web-{{.CurrentEnvironment}}
  labels:
    project: go-xample
    service: web
    env: {{.CurrentEnvironment}}
spec:
  replicas: {{.CurrentReplica}}
  selector:
    matchLabels:
      project: go-xample
      service: web
      env: {{.CurrentEnvironment}}
  template:
    metadata:
      labels:
        project: go-xample
        service: web
        release: '{{.Version}}'
        env: {{.CurrentEnvironment}}
    spec:
      imagePullSecrets:
      - name: blregistry
      containers:
      - name: go-xample-web
        image: registry.bukalapak.io/bukalapak/go-xample/web:{{.Version}}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 1234
          initialDelaySeconds: 30
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 1234
          timeoutSeconds: 1
        ports:
        - containerPort: 1234
        command:
          - envconsul
          - -consul=127.0.0.1:8500
          - -sanitize
          - -upcase
          - -prefix=go-xample
          - web
      - name: consul
        image: registry.bukalapak.io/bukalapak/consul-image:0.0.10
        env:
        - name: SERVICE_NAME
          value: go-xample-web
        - name: SERVICE_ENVIRONMENT
          value: {{.CurrentEnvironment}}
        - name: SERVICE_PORT
          value: "1234"
        - name: CONSUL1
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: node1
        - name: CONSUL2
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: node2
        - name: CONSUL3
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: node3
        - name: CONSUL_ENCRYPT
          valueFrom:
            configMapKeyRef:
              name: consul-config
              key: encrypt
        ports:
        - containerPort: 8300
        - containerPort: 8301
        - containerPort: 8302
        - containerPort: 8400
        - containerPort: 8500
        - containerPort: 8600
        command: [ entrypoint, agent, -config-dir=/config, -join=$(CONSUL1), -join=$(CONSUL2), -join=$(CONSUL3), -encrypt=$(CONSUL_ENCRYPT) ]
      nodeSelector:
        env: production
