development:
  adapter: mysql2
  database: <%= ENV['MYSQL_DATABASE'] || 'go_xample_development' %>
  host: <%= ENV['MYSQL_HOST'] || '127.0.0.1' %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: <%= ENV['MYSQL_DATABASE'] || 'production db_name' %>
  pool: <%= ENV['MYSQL_POOL'] || 5 %>
  username: <%= ENV['MYSQL_USERNAME'] || 'username' %>
  password: <%= ENV['MYSQL_PASSWORD'] || 'password' %>
