apiVersion: v1
kind: Service
metadata:
  name: "go-xample-background-job-{{.CurrentEnvironment}}"
spec:
  selector:
    project: go-xample
    service: background-job
    env: {{.CurrentEnvironment}}
  ports:
    - protocol: TCP
      port: 1235
      targetPort: 1235
      nodePort: {{.NodePort}}
  type: NodePort
